-- Dropping procedures first to ensure no dependency issues
DROP PROCEDURE IF EXISTS GetContacts();
DROP PROCEDURE IF EXISTS GetName();

-- Dropping tables
DROP TABLE IF EXISTS CONTACTS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS LOCATIONS;
DROP TABLE IF EXISTS SALESTEAM;
