
name: deployToBuild
 
# Controls when the workflow will run
on:
  workflow_dispatch:
 
jobs:
  build:
    name: Deploy Build
    runs-on: ubuntu-latest
    container: 
        image: flyway/flyway
    environment: 'build' 
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      JDBC: ${{ secrets.JDBC_URL }}
      
      displayName: 'Build'
 
    steps:
      - uses: actions/checkout@v4

      # Runs the Flyway Clean command against the Build database
      #- name: INFO
      #  run: flyway info -environment=build -environments.build.url="${{ env.JDBC }}" -environments.build.user="${{ env.USERNAME }}" -environments.build.password="${{ env.PASSWORD }}" -environments.build.schemas=public -cleanDisabled="false" 
        
        
        # Runs the Flyway Migrate command against the Build database
      - name: Migrate Build DB
        run: flyway info migrate info  -baselineOnMigrate="true" -environment=build -environments.build.user="${{ env.USERNAME }}" -environments.build.password="${{ env.PASSWORD }}" -baselineOnMigrate="true"   -environments.build.url="${{ env.JDBC }}" -cleanDisabled="false"
    
