
name: deployToProduction
 
# Controls when the workflow will run
on:
  workflow_dispatch:
 
jobs:
  test:
    name: Deploy Test
    runs-on: ubuntu-latest
    container: 
        image: flyway/flyway
    environment: 'test' 
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      JDBC: ${{ secrets.JDBC_URL }}
      
      displayName: 'Test'
 
    steps:
      - uses: actions/checkout@v4

        
      # Runs the Flyway Migrate command against the Test database
      - name: Migrate test DB
        run: flyway info migrate info  -environment=test -environments.test.user="${{ env.USERNAME }}" -environments.test.password="${{ env.PASSWORD }}" -baselineOnMigrate="true"   -environments.test.url="${{ env.JDBC }}" 
    
  prod:
   name: Deploy Prod
   needs: test
   runs-on: ubuntu-latest
   container: 
       image: flyway/flyway
   environment: 'prod'
   env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      JDBC: ${{ vars.test }}
      displayName: 'Prod'
   steps:
   - uses: actions/checkout@v4
   - name: testing
     run: echo ${{ vars.test }}
   # Runs the Flyway Migrate command against the Test database
   - name: Migrate prod DB
     run: flyway info migrate info  -environment=prod -environments.prod.user="${{ env.USERNAME }}" -environments.prod.password="${{ env.PASSWORD }}" -baselineOnMigrate="true"   -environments.prod.url="${{ env.JDBC }}" 

   
   
  
